# Generated by Django 3.2.5 on 2023-02-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('area_code', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
    ]
