# Generated by Django 4.1.5 on 2023-02-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0002_goods_sales_rename_customer_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='ct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
