# Generated by Django 3.2.5 on 2023-03-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0002_auto_20230307_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='salermonthlysalerating',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salermonthlysalerating',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salermonthlysalerating',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
