# Generated by Django 3.2.5 on 2023-03-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0003_auto_20230307_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerperformance',
            name='date',
        ),
        migrations.AddField(
            model_name='salerperformance',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salerperformance',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
