# Generated by Django 3.2.5 on 2023-03-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0003_delete_omer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalerReceipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('sale_rating', models.FloatField(default=1, null=True)),
            ],
        ),
    ]
