# Generated by Django 4.1.5 on 2023-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0003_alter_sales_ct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='additional_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount_sale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='bill_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='bonus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='bonus_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='discount_percentage_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='dollar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='good_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='manager_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='net_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='original_output_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='original_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_cash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_check',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='prim_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='real_discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='receipment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='saler_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='secondary_output_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='senior_saler',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tot_monthly_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
