# Generated by Django 3.2.5 on 2023-03-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0004_salerreceiperating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salermonthlysalerating',
            name='day',
        ),
        migrations.AddField(
            model_name='salermonthlysalerating',
            name='name',
            field=models.CharField(default='omer', max_length=100),
            preserve_default=False,
        ),
    ]
