# Generated by Django 3.2.5 on 2023-03-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0004_auto_20230307_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salermonthlysalerating',
            name='date',
        ),
    ]
