# Generated by Django 3.2.5 on 2023-03-10 08:18

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0005_remove_salermonthlysalerating_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.IntegerField(null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('piece', models.FloatField(null=True)),
                ('sale', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
