# Generated by Django 4.1.5 on 2023-02-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0005_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
