# Generated by Django 4.1.5 on 2023-02-20 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0006_alter_warehouse_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='day',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='month',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='year',
        ),
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
