# Generated by Django 4.1.5 on 2023-03-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0006_monthlyproductsales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyproductsales',
            name='day',
        ),
    ]
