# Generated by Django 3.2.5 on 2023-03-11 12:27

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0007_remove_monthlyproductsales_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyproductsales',
            name='date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
