# Generated by Django 3.2.5 on 2023-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0008_auto_20230223_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='product_number_ir',
            field=models.IntegerField(unique=True),
        ),
    ]
