# Generated by Django 3.2.5 on 2023-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0008_alter_monthlyproductsales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyproductsales',
            name='piece',
            field=models.FloatField(default=0, null=True),
        ),
    ]
