# Generated by Django 4.1.5 on 2023-02-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0010_alter_pricelist_product_number_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='dollar',
            field=models.FloatField(null=True),
        ),
    ]
