# Generated by Django 4.1.5 on 2023-02-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0011_alter_pricelist_dollar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('subgroup', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
                ('product_code_ir', models.IntegerField(unique=True)),
                ('product_code_tr', models.FloatField(null=True)),
                ('description_tr', models.CharField(max_length=400)),
                ('description_ir', models.CharField(max_length=400)),
                ('unit', models.CharField(max_length=255)),
                ('unit_secondary', models.CharField(max_length=255)),
                ('weight', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=255)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('subgroup', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=100)),
                ('new_or_old_product', models.CharField(blank=True, max_length=100, null=True)),
                ('related', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code_ir', models.CharField(max_length=100)),
                ('product_code_tr', models.CharField(max_length=100)),
                ('dont_order_again', models.CharField(blank=True, max_length=100, null=True)),
                ('description_tr', models.CharField(blank=True, max_length=100, null=True)),
                ('description_ir', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_secondary', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('avarage_previous_year', models.FloatField(blank=True, null=True)),
                ('month_1', models.FloatField(blank=True, null=True)),
                ('month_2', models.FloatField(blank=True, null=True)),
                ('month_3', models.FloatField(blank=True, null=True)),
                ('month_4', models.FloatField(blank=True, null=True)),
                ('month_5', models.FloatField(blank=True, null=True)),
                ('month_6', models.FloatField(blank=True, null=True)),
                ('month_7', models.FloatField(blank=True, null=True)),
                ('month_8', models.FloatField(blank=True, null=True)),
                ('month_9', models.FloatField(blank=True, null=True)),
                ('month_10', models.FloatField(blank=True, null=True)),
                ('month_11', models.FloatField(blank=True, null=True)),
                ('month_12', models.FloatField(blank=True, null=True)),
                ('total_sale', models.FloatField(blank=True, null=True)),
                ('warehouse', models.FloatField(blank=True, null=True)),
                ('goods_on_the_road', models.FloatField(blank=True, null=True)),
                ('total_stock_all', models.FloatField(blank=True, null=True)),
                ('total_month_stock', models.FloatField(blank=True, null=True)),
                ('standart_deviation', models.FloatField(blank=True, null=True)),
                ('lead_time', models.FloatField(blank=True, null=True)),
                ('product_coverage_percentage', models.FloatField(blank=True, null=True)),
                ('demand_status', models.CharField(blank=True, max_length=100, null=True)),
                ('safety_stock', models.FloatField(blank=True, null=True)),
                ('rop', models.FloatField(blank=True, null=True)),
                ('monthly_mean', models.FloatField(blank=True, null=True)),
                ('new_party', models.CharField(blank=True, max_length=100, null=True)),
                ('cycle_service_level', models.FloatField(blank=True, null=True)),
                ('total_stock', models.FloatField(blank=True, null=True)),
                ('need_prodcuts', models.FloatField(blank=True, null=True)),
                ('over_stock', models.FloatField(blank=True, null=True)),
                ('calculated_need', models.FloatField(blank=True, null=True)),
                ('calculated_max_stock', models.FloatField(blank=True, null=True)),
                ('calculated_min_stock', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
