# Generated by Django 3.2.5 on 2023-03-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0011_productperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerperformance',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
