# Generated by Django 4.1.5 on 2023-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0012_products_rop_delete_goods_delete_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_code_tr',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
