# Generated by Django 3.2.5 on 2023-02-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0013_alter_products_product_code_tr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_start_date', models.DateField(null=True)),
                ('manager_performance_rating', models.FloatField(null=True)),
                ('experience_rating', models.FloatField(null=True)),
                ('monthly_total_sales_rating', models.FloatField(null=True)),
                ('receipment_rating', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sales',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='currency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sales',
            name='group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sales',
            name='psr',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sales',
            name='unit',
            field=models.CharField(max_length=30),
        ),
    ]
