# Generated by Django 4.1.5 on 2023-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0013_alter_products_product_code_tr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_start_date', models.DateField(null=True)),
                ('manager_performance_rating', models.FloatField(null=True)),
                ('experience_rating', models.FloatField(null=True)),
                ('monthly_total_sales_rating', models.FloatField(null=True)),
                ('receipment_rating', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
