# Generated by Django 3.2.5 on 2023-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0013_auto_20230315_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='productperformance',
            name='sale_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rop',
            name='dont_order_again',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
