# Generated by Django 3.2.5 on 2023-02-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0014_auto_20230225_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='no',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
