# Generated by Django 3.2.5 on 2023-03-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0015_auto_20230317_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerperformance',
            name='sale_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
