# Generated by Django 3.2.5 on 2023-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0016_customerperformance_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='unit2',
            field=models.CharField(max_length=30),
        ),
    ]
