# Generated by Django 4.1.5 on 2023-02-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0014_salers'),
        ('stockfish_api', '0017_alter_salerperformance_sale'),
    ]

    operations = [
    ]
