# Generated by Django 3.2.5 on 2023-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0017_alter_sales_unit2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerperformance',
            name='customer_area',
            field=models.CharField(default='tehran', max_length=100),
            preserve_default=False,
        ),
    ]
