# Generated by Django 3.2.5 on 2023-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0018_customerperformance_customer_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerperformance',
            name='dollar',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customerperformance',
            name='dollar_sepidar',
            field=models.FloatField(default=0, null=True),
        ),
    ]
