# Generated by Django 3.2.5 on 2023-04-06 12:18

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0019_auto_20230328_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(null=True)),
                ('order_flag_avrg', models.BooleanField()),
                ('order_flag_exp', models.BooleanField()),
                ('order_flag_holt', models.BooleanField()),
                ('order_avrg', models.FloatField(default=0, null=True)),
                ('order_exp', models.FloatField(default=0, null=True)),
                ('order_holt', models.FloatField(default=0, null=True)),
                ('current_date', models.DateField()),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('decided_order', models.FloatField(default=0, null=True)),
                ('weight', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
