# Generated by Django 3.2.5 on 2023-04-06 12:37

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0020_orderlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='date',
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='current_date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
