# Generated by Django 3.2.5 on 2023-04-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0021_auto_20230406_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='average_sale',
            field=models.FloatField(default=0, null=True),
        ),
    ]
