# Generated by Django 4.1.5 on 2023-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0022_orderlist_average_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='product_code',
            field=models.IntegerField(null=True),
        ),
    ]
