# Generated by Django 3.2.5 on 2023-04-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0023_orderlist_is_active_orderlist_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='is_ordered',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='current_stock',
            field=models.FloatField(default=0, null=True),
        ),
    ]
