# Generated by Django 3.2.5 on 2023-04-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0024_auto_20230407_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsOnRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField(null=True)),
                ('product_name_tr', models.CharField(max_length=100)),
                ('product_name_ir', models.CharField(max_length=100)),
                ('decided_order', models.FloatField(default=0, null=True)),
                ('weight', models.FloatField(default=0, null=True)),
                ('truck_id', models.CharField(max_length=100)),
                ('is_ordered', models.BooleanField()),
                ('is_terminated', models.BooleanField(default=False)),
                ('is_on_truck', models.BooleanField()),
            ],
        ),
    ]
