# Generated by Django 3.2.5 on 2023-04-18 10:27

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0025_goodsonroad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=100)),
                ('estimated_order_date', django_jalali.db.models.jDateField(null=True)),
                ('estimated_arrival_date', django_jalali.db.models.jDateField(null=True)),
                ('is_arrived', models.BooleanField(default=False)),
                ('is_ordered', models.BooleanField()),
            ],
        ),
    ]
