# Generated by Django 4.1.5 on 2023-04-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0027_rename_truck_id_goodsonroad_truck_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsonroad',
            name='is_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trucks',
            name='is_waiting',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trucks',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
