# Generated by Django 4.1.5 on 2023-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0028_goodsonroad_is_arrived_trucks_is_waiting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsonroad',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
