# Generated by Django 3.2.5 on 2023-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0029_alter_goodsonroad_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerperformance',
            name='customer_code',
            field=models.IntegerField(default=999999, unique=True),
            preserve_default=False,
        ),
    ]
