# Generated by Django 3.2.5 on 2023-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0030_alter_customerperformance_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
