# Generated by Django 3.2.5 on 2023-04-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0031_auto_20230425_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerperformance',
            name='customer_code',
            field=models.IntegerField(),
        ),
    ]
