# Generated by Django 3.2.5 on 2023-04-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0032_alter_customerperformance_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salers',
            name='is_active_saler',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salers',
            name='is_passive_saler',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
