# Generated by Django 4.1.5 on 2023-05-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0034_notificationsorderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerperformance',
            name='bonus',
            field=models.FloatField(default=0, null=True),
        ),
    ]
