# Generated by Django 4.1.5 on 2023-06-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0035_salerperformance_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='discount_percentage_2',
            new_name='original_price_dollar',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='original_output_value',
            new_name='price_dollar',
        ),
        migrations.RemoveField(
            model_name='products',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='salermonthlysalerating',
            name='day',
        ),
        migrations.RemoveField(
            model_name='salerreceiperating',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='real_discount_percentage',
        ),
        migrations.AddField(
            model_name='salerreceiperating',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salerreceiperating',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salerreceiperating',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product_code_tr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
