# Generated by Django 4.1.5 on 2023-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0036_rename_discount_percentage_2_sales_original_price_dollar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsonroad',
            name='suppliers',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='suppliers',
            field=models.CharField(default='s', max_length=400),
            preserve_default=False,
        ),
    ]
