# Generated by Django 3.2.5 on 2023-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0037_goodsonroad_suppliers_products_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='color_making_saler',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
