# Generated by Django 3.2.5 on 2023-07-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0038_alter_sales_color_making_saler'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='gregorian_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
