# Generated by Django 3.2.5 on 2023-08-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0040_alter_sales_psr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='saler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
