# Generated by Django 3.2.5 on 2023-08-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockfish_api', '0041_alter_sales_saler'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
