from django.db import models
class Customers(models.Model):
    customer_code = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=200)
    quantity = models.IntegerField()
    area_code = models.CharField(max_length=100)
    code = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    area = models.CharField(max_length=100)
    def __str__(self):
        return self.customer_code
class Goods(models.Model):
    product_code = models.IntegerField(unique=True)
    group = models.CharField(max_length=200)
    product_title = models.CharField(max_length=100)
    unit_title = models.CharField(max_length=100)
    unit = models.CharField(max_length=100)
    currency = models.CharField(max_length=100)
    f = models.CharField(max_length=100)
    def __str__(self):
        return self.product_code
class Sales(models.Model):
    no = models.PositiveIntegerField(unique=True)
    bill_number = models.PositiveIntegerField(null=True, blank=True)
    date = models.DateField(null= True)
    psr = models.CharField(max_length=100)
    customer_code = models.PositiveIntegerField(null=True, blank=True)
    name = models.CharField(max_length=100)
    area = models.CharField(max_length=100)
    group = models.CharField(max_length=100)
    good_code = models.PositiveIntegerField(null=True, blank=True)
    goods = models.CharField(max_length=100)
    unit = models.CharField(max_length=100)
    original_value = models.FloatField(null=True, blank=True)
    original_output_value = models.FloatField(null=True, blank=True)
    secondary_output_value = models.FloatField(null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    original_price = models.FloatField(null=True, blank=True)
    discount_percentage = models.FloatField(null=True, blank=True)
    amount_sale = models.FloatField(null=True, blank=True)
    discount = models.FloatField(null=True, blank=True)
    additional_sales = models.FloatField(null=True, blank=True)
    net_sales = models.FloatField(null=True, blank=True)
    discount_percentage_2 = models.FloatField(null=True, blank=True)
    real_discount_percentage = models.FloatField(null=True, blank=True)
    payment_cash = models.FloatField(null=True, blank=True)
    payment_check = models.FloatField(null=True, blank=True)
    balance = models.FloatField(null=True, blank=True)
    saler = models.CharField(max_length=100)
    currency = models.CharField(max_length=100)
    dollar = models.FloatField(null=True, blank=True)
    manager_rating = models.FloatField(null=True, blank=True)
    senior_saler = models.FloatField(null=True, blank=True)
    tot_monthly_sales = models.FloatField(null=True, blank=True)
    receipment = models.FloatField(null=True, blank=True)
    ct = models.FloatField(null=True, blank=True)
    payment_type = models.CharField(max_length=100)
    customer_size = models.FloatField(null=True, blank=True)
    saler_factor = models.FloatField(null=True, blank=True)
    prim_percentage = models.FloatField(null=True, blank=True)
    bonus_factor = models.FloatField(null=True, blank=True)
    bonus = models.FloatField(null=True, blank=True)
    def __str__(self):
        return self.no

class Warehouse(models.Model):
    product_code = models.IntegerField(unique=True)
    title = models.CharField(max_length=200)
    unit = models.CharField(max_length=50)
    stock = models.FloatField(null=True, blank=True)

class PriceList(models.Model):
    group = models.CharField(max_length=255)
    subgroup = models.CharField(max_length=255)
    feature = models.CharField(max_length=255)
    product_number_ir = models.IntegerField(unique= True)
    product_number_tr = models.CharField(max_length=255)
    description_tr = models.CharField(max_length=400)
    description_ir = models.CharField(max_length=400)
    unit = models.CharField(max_length=255)
    unit_secondary = models.CharField(max_length=255)
    dollar = models.FloatField(null= True)